import eslint from "eslint";

/**
 *  This is not a node generated by es-html-parser; it is created by utils's splitToLineNodes.
 */
export interface Line {
  type: "Line";
  value: string;
  hasTemplate: boolean;
  range: eslint.AST.Range;
  loc: eslint.AST.SourceLocation;
}
