import type { CloseTemplate, OpenTemplate } from "@html-eslint/types";
import eslint, { type AST } from "eslint";

/**
 * This is not a node generated by es-html-parser; it is created by utils's
 * splitToLineNodes.
 */
export interface Line extends BaseNode {
  type: "Line";
  value: string;
  withinTemplate: boolean;
}

export interface BaseNode {
  parent?: BaseNode | null;
  type: string;
  range: eslint.AST.Range;
  loc: eslint.AST.SourceLocation;
}
