import eslint from "eslint";

/**
 * This is not a node generated by es-html-parser; it is created by utils's
 * splitToLineNodes.
 */
export interface Line extends BaseNode {
  type: "Line";
  value: string;
  isOverlapTemplate: boolean;
  hasOpenTemplate: boolean;
  hasCloseTemplate: boolean;
}

export interface BaseNode {
  parent?: BaseNode | null;
  type: string;
  range: eslint.AST.Range;
  loc: eslint.AST.SourceLocation;
}
